ci:
  - head-branch: ["^v\\d+/ci/", "^ci/"]

feature:
  - head-branch: ["^v\\d+/feat/", "^feat/"]

bug:
  - head-branch: ["^v\\d+/fix/", "^fix/"]

documentation:
  - head-branch: ["^v\\d+/docs/", "^docs/"]
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "docs/**/*"]

refactor:
  - head-branch: ["^v\\d+/refactor/", "^refactor/"]

test:
  - head-branch: ["^v\\d+/test/", "^test/"]
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.test.ts"
          - "**/*.test.tsx"
          - "**/*.spec.ts"
          - "**/*.spec.tsx"
          - "e2e/**/*"

performance:
  - head-branch: ["^v\\d+/perf/", "^perf/"]

chore:
  - head-branch: ["^v\\d+/chore/", "^chore/"]
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
          - "*.config.*"
          - "*.json"
          - "*.yaml"
          - "*.yml"
